services:
  redis:
    build: ./redis
    container_name: redis-server
    depends_on:
      - vault
      - vault-agent
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - tls_certs:/certs:ro
#    restart: unless-stopped
    networks:
      - backend
  app:
    build: .
    container_name: tiny-url-app
    depends_on:
      - redis
      - vault
      - vault-agent
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    volumes:
      - tls_certs:/app/certs
    networks:
      - backend
  vault:
    image: hashicorp/vault:1.21
    container_name: vault-server
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: ["vault", "server", "-config=/vault/config/vault.hcl"]
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
    networks:
      - backend
  vault-agent:
    image: hashicorp/vault:1.21
    container_name: vault-agent
    depends_on:
      - vault
    volumes:
      - ./vault/agent/config/vault-agent.hcl:/vault/agent/config/vault-agent.hcl
      - ./vault/agent/templates:/vault/agent/templates
      - ./vault/agent/logs:/vault/agent/logs
      - ./vault/agent/auth:/vault/agent/auth
      - tls_certs:/home/vault
    command: ["vault", "agent", "-config=/vault/agent/config/vault-agent.hcl"]
    networks:
      - backend
volumes:
  redis_data:
  tls_certs:
networks:
  backend:
    driver: bridge